[player]
mass = [60.0] # kg
force = [1000.0] # N
jumpForce = [46_000.0] # N
upGravity = [8.0] # tiles/s^2
downGravity = [32.0] # tiles/s^2
groundFriction = [3.0]
airFriction = [0.5]
velocityCap = [5.5] # tiles/s
jumpDelay = [4] # ticks

[physics]
cornerMargin = [5.0]

[tile] # not dynamically configurable
metreSize = [40]
size = [24]
