[player]
mass = [60.0] # kg
force = [500.0] # N
jumpForce = [46_000.0] # N
upGravity = [9.8] # tiles/s^2
downGravity = [24.0] # tiles/s^2
groundFriction = [0.8]
velocityCap = [5.5] # tiles/s
jumpDelay = [4] # ticks
cornerMargin = [5.0]

[tile] # not dynamically configurable
metreSize = [40]
size = [24]
